name: Python application
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: qwer33/flask
        tags: ${{ github.sha }}
        registry: docker.io
        username: qwer33
        password: dckr_pat_Utwi8XM7-CvS1tI9r8QCTK42IlI
        
    - name: 'Deploy to Azure Web App1'      
      uses: azure/webapps-deploy@v2      
      with:
       app-name: 'cdgithubaction67'
       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
       images: 'qwer33/flask:${{ github.sha }}'

